name: Development Pipeline

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.info.outputs.version }}
          build-args: |
            build_script=bk:build:prod

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      - name: Run commands on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          key: ${{secrets.PRODUCTION_SERVER_KEY}}
          script: |
            docker login -u ${{secrets.CI_ACCESS_USER}} -p ${{secrets.CI_ACCESS_TOKEN}} ghcr.io
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.info.outputs.version }}
            docker stop ${{github.event.repository.name}} || true
            docker rm ${{github.event.repository.name}} || true
            docker run --restart=always -d -p ${{secrets.DEPLOYMENT_PORT}}:80 --name=${{github.event.repository.name}} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.info.outputs.version }}
